name: docker image

on:
  push:
    branches-ignore: [gh-pages]

jobs:
  buildx:
    strategy:
      matrix:
        images:
        - calc
        - jhd
        - jupyter
        - pdfcrop
        - sqlite3
        - optipng
        - zopflipng
        - grpcui
        - uuidgen_linux
        - lftp
        - ncftp
        - rsync
        - gifsicle
        - gif-for-cli
        - csvq
        - sysbench
        - sslscan
        - cscope
        - git-webui
        - genisoimage
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v2
       with:
         lfs: true
     - name: setup qemu
       uses: docker/setup-qemu-action@v1
     - name: setup docker buildx
       id: buildx
       uses: docker/setup-buildx-action@v1
     - name: login ghcr.io
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.CR_PAT }}
     - name: build and push
       uses: docker/build-push-action@v2
       with:
         #platforms: ${{ steps.buildx.outputs.platforms }}
         platforms: linux/amd64,linux/arm64,linux/arm/v7
         push: true
         context: ${{ matrix.images }}
         file: ${{ matrix.images }}/Dockerfile
         tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.images }}:latest
