name: docker image (x64)

on:
  push:
    branches-ignore: [gh-pages]

jobs:
  buildx:
    strategy:
      matrix:
        images:
        - kubebuilder
        - randgen
        - duckdb
        - pandoc
        - wasmtime
        - wasmer
        - wamr
        # - jupyter-pyston
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: setup docker buildx
       id: buildx
       uses: docker/setup-buildx-action@v1
     - name: login ghcr.io
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.CR_PAT }}
     - name: build and push
       uses: docker/build-push-action@v2
       with:
         platforms: linux/amd64
         push: true
         context: ${{ matrix.images }}
         file: ${{ matrix.images }}/Dockerfile
         tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.images }}:latest
