name: docker image

on:
  push:
    branches-ignore: [gh-pages]

jobs:
  buildx:
    strategy:
      matrix:
        images:
        - calc
        - jhd
        - jupyter
        - kubebuilder
        - pdfcrop
        - randgen
        - sqlite3
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v2
     - name: setup qemu
       uses: docker/setup-qemu-action@v1
     - name: setup docker buildx
       id: buildx
       uses: docker/setup-buildx-action@v1
     - name: login ghcr.io
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         password: ${{ secrets.CR_PAT }}
     - name: build and push
       uses: docker/build-push-action@v2
       with:
         registry: ghcr.io
         platforms: ${{ steps.buildx.outputs.platforms }}
         push: true
         context: ${{ matrix.images }}
         dockerfile: ${{ matrix.images }}/Dockerfile
         tags:
           - ghcr.io/${{ github.repository_owner }}/${{ matrix.images }}:latest
