name: entrypoint

on:
  push:
    branches-ignore: [gh-pages]

jobs:
  generate_entrypoint:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: setup python ${{ matrix.pyver }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: install modules
      run: pip install -r requirements.txt
    - name: build entrypoint
      run: |
        python generate.py entrypoint.sh.j2 vars.yaml
